# Generated by Django 3.2.8 on 2022-02-16 12:40

from django.db import migrations, models
import home.validators


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='photo_url',
            field=models.CharField(max_length=200, validators=[home.validators.validate_url]),
        ),
        migrations.AlterField(
            model_name='about',
            name='resume_url',
            field=models.CharField(max_length=200, validators=[home.validators.validate_url]),
        ),
    ]
