# Generated by Django 3.2.8 on 2022-02-22 08:22

from django.db import migrations, models
import home.validators


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='photo_url',
            field=models.CharField(default='https://drive.google.com/uc?export=view&id=', max_length=200, validators=[home.validators.validate_url]),
        ),
    ]
