# Generated by Django 3.2.8 on 2022-02-25 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_about_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalsummary',
            name='content',
            field=models.TextField(max_length=200),
        ),
    ]
