# Generated by Django 3.2.8 on 2022-03-08 13:57

import django.core.validators
from django.db import migrations, models
import home.validators


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_professionalsummary_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AddField(
            model_name='about',
            name='github_url',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[home.validators.validate_url]),
        ),
        migrations.AddField(
            model_name='about',
            name='linked_in_url',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[home.validators.validate_url]),
        ),
        migrations.AddField(
            model_name='about',
            name='twitter_url',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[home.validators.validate_url]),
        ),
    ]
