# Generated by Django 3.2.8 on 2022-02-18 03:22

from django.db import migrations, models
import home.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('o', 'On Going'), ('c', 'Completed')], default='c', max_length=1)),
                ('platform', models.CharField(max_length=20)),
                ('genre', models.CharField(max_length=100)),
                ('engine', models.CharField(max_length=20)),
                ('language', models.CharField(max_length=10)),
                ('team', models.TextField()),
                ('play_url', models.CharField(max_length=200, validators=[home.validators.validate_url])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
