# Generated by Django 3.2.8 on 2022-02-18 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_gamedetail_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamedetail',
            name='project',
        ),
        migrations.AddField(
            model_name='gameproject',
            name='detail',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.gamedetail'),
            preserve_default=False,
        ),
    ]
