# Generated by Django 3.2.8 on 2022-02-21 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20220218_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalPurposedProject',
            fields=[
                ('gameproject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.gameproject')),
            ],
            bases=('game.gameproject',),
        ),
        migrations.CreateModel(
            name='MyProject',
            fields=[
                ('gameproject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.gameproject')),
            ],
            bases=('game.gameproject',),
        ),
    ]
