# Generated by Django 3.2.8 on 2022-02-23 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_gamecarousel_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedetail',
            name='engine',
            field=models.CharField(default='Unity', max_length=20),
        ),
        migrations.AlterField(
            model_name='gamedetail',
            name='language',
            field=models.CharField(default='C#', max_length=10),
        ),
    ]
