# Generated by Django 3.2.8 on 2022-03-08 09:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_gameproject_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedetail',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
