# Generated by Django 3.2.8 on 2022-03-08 09:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_gamedetail_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamedetail',
            name='release_date',
        ),
        migrations.AddField(
            model_name='gameproject',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
